usdot-fhwa-stol/carma-analytics-fotda

src/rosbag_analysis_tools/scripts/analyze_TIM_and_RWM_rosbags.py
src/rosbag_analysis_tools/scripts/analyze_basic_travel_rosbags.py
src/rosbag_analysis_tools/scripts/analyze_freight_workzone_rosbags.py
src/rosbag_analysis_tools/scripts/analyze_ihp2_rosbags.py
src/rosbag_analysis_tools/scripts/analyze_port_drayage_rosbags.py
src/rosbag_analysis_tools/scripts/analyze_tsmo_uc2_rosbags.py
src/rosbag_analysis_tools/scripts/analyze_voices_sit1_rosbags.py
src/rosbag_analysis_tools/scripts/analyze_wz_rosbags.py

This PR includes several rosbag analysis scripts that have been used to analyze CARMA Platform, V2XHub, and CARMA Cloud performance for a number of use cases over the past year. These analysis scripts have been developed to evaluate system performance typically with regards to a set of defined metrics. The analysis scripts included are listed below:
- analyze_TIM_and_RWM_rosbags.py
- analyze_basic_travel_rosbags.py
- analyze_freight_workzone_rosbags.py
- analyze_ihp2_rosbags.py
- analyze_port_drayage_rosbags.py
- analyze_tsmo_uc2_rosbags.py
- analyze_voices_sit1_rosbags.py
- analyze_wz_rosbags.py
NOTE: This PR is being created to move the rosbag analysis scripts from carma-platform to carma-analytics-fotda. Related CARMA Platform PR: [Click …

Add scripts for analyzing CARMA System performance for different use cases

---

.gitignore
tsmo/src/one_veh_et_spat_plotter.py
tsmo/src/vehicle_dist_time_with_spat_plotter.py

Added grid lines and minor ticks to one vehicle et plots and vehicle vs distance plots
Added gridlines and minor ticks to plot
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-analytics-fotda/blob/main/Contributing.md)

Added Grid lines and minor ticks to plots

---

tsmo/src/tsc_service_log_parser.py
tsmo/src/tsc_service_spat_processing_time_parser.py

Added parser for the tsc_service log file to parse out spat processing times. The terminal logs print out an average over 2 second intervals in milliseconds. This script parses out that value, along with the terminal log statement timestamp and then creates a csv file with timestamp (ms) and processing time (ms)
Collect performance metrics for TSMO UC3
Locally tested with terminal log file
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-analytics-fotda/blob/main/Contributing.md)

Added tsc_service_spat_processing_time_parser

---

src/ros2_tracing_analysis_tools/carma_analyze_callback_durations.py

Support was recently added to CARMA Platform for logging trace data from a test run using `ros2_tracing`, but a script is required to enable a user to process the trace data and extract meaningful information from the trace data. The `carma_analyze_callback_durations.py` script was developed for this, and it is based off of a Jupyter Notebook developed specifically for `ros2_tracing` trace sessions [(Link Here)](https://github.com/ros-tracing/tracetools_analysis/blob/foxy/tracetools_analysis/analysis/callback_duration.ipynb). 
The script includes instructions for a user to setup their workspace appropriately, install dependencies, and run the script with a known trace session on the user's PC.
Related PRs:
- carma-base: [#183](https://github.com/usdot-fhwa-stol/carma-base/pull/183)
- …

Add script for analyzing 'ros2_tracing' trace sessions from CARMA Platform

---

vru_use_case_scripts/README.md
vru_use_case_scripts/extract_rtf_data
vru_use_case_scripts/plot_rtf_data

This PR adds helper scripts specific to the VRU use case.
Closes [CDAR-749](https://usdot-carma.atlassian.net/browse/CDAR-749)
Manually
[CDAR-749]: https://usdot-carma.atlassian.net/browse/CDAR-749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add VRU helper scripts

---

src/carma-streets/parse_kafka_logs.py

Add methods to parse SDSM and MAP data from Kafka topic logs
Added logic to account for multiline json 
CDAR-535
Data Analysis (Message Frequency Plots)

Add MAP and SDSM parsing

---

src/carma-streets/parse_kafka_logs.py

Updates to correct SPAT and SDSM timestamp
- SDSM timestamp updated to account for microsecond parameter in datetime constructor
- Added simulation argument to script for SPAT timestamp in simulation to be relative to unix epoch so that all timestamp data is relative to the same year
CDAR-535
Fix script
Local testing with CDASim collected data.

Fix SDSM and SPAT timestamp

---

src/carma-streets/parse_kafka_logs.py

Added parsing for detected objects to the `parse_kafka_logs.py` script
CDAR-535
Data analysis
Tested using CDASim collected data

CDAR-535: Added parsing for detected objects

---

src/carma-platform/parse_ros_bags.py

This PR adds odometry rosbag parsing for the vehicle's odometry information.
Closes [CDAR-852](https://usdot-carma.atlassian.net/browse/CDAR-852)
Verification testing metric.
[CDAR-852]: https://usdot-carma.atlassian.net/browse/CDAR-852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Tracking:
@MishkaMN

Add vehicle odometry parsing for rosbags

---

vru_use_case_scripts/README.md

There was a mistype in the README that was not displaying the example plot.
See above

Update README.md for example_missing_object_duration

---

vru_use_case_scripts/plot_sdsm_position_error

Closes [CDAR-872](https://usdot-carma.atlassian.net/browse/CDAR-872)
[CDAR-872]: https://usdot-carma.atlassian.net/browse/CDAR-872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

`plot_sdsm_position_error` Add optional argument for plot save location

---

vru_use_case_scripts/plot_detected_objects

Closes [CDAR-869](https://usdot-carma.atlassian.net/browse/CDAR-869)
[CDAR-869]: https://usdot-carma.atlassian.net/browse/CDAR-869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

`plot_detected_objects` Add optional argument for plot save location

---

vru_use_case_scripts/plot_rtf_data

Closes [CDAR-871](https://usdot-carma.atlassian.net/browse/CDAR-871)
[CDAR-871]: https://usdot-carma.atlassian.net/browse/CDAR-871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

`plot_rtf_data` Add optional argument for plot save location

---

vru_use_case_scripts/plot_time_to_collision

Closes [CDAR-873](https://usdot-carma.atlassian.net/browse/CDAR-873)
[CDAR-873]: https://usdot-carma.atlassian.net/browse/CDAR-873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

`plot_time_to_collision` Add optional argument for plot save location

---

vru_use_case_scripts/plot_missing_object_durations

Closes [CDAR-870](https://usdot-carma.atlassian.net/browse/CDAR-870)
[CDAR-870]: https://usdot-carma.atlassian.net/browse/CDAR-870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

`plot_missing_object_durations` Add optional argument for plot save location

---

vru_use_case_scripts/README.md
vru_use_case_scripts/plot_detected_objects
vru_use_case_scripts/run_all_analysis_scripts

This PR adds a top-level script that invokes all the scripts belonging to the VRU use case analysis.
Closes [CDAR-866](https://usdot-carma.atlassian.net/browse/CDAR-866)
Convenience script for automating analysis on runs
Manually tested with some captured simulation data

Add top-level script to invoke all VRU use case analysis scripts

---

vru_use_case_scripts/run_all_analysis_scripts

This PR attempts to fix the issue where sometimes txt files are not populated with the results from the process. 
Individual scripts logic themselves that print to a txt file don't have a problem (I got results fine from all through runs). 
However, I did see that it was not populating when I first tried it. 
When I started debugging by printing the results in the main script, it started working fine consistently, so not sure why or when it fails.
Therefore, currently this PR:
1) forces to print the output which hopefully fixes the issue altogether mimicking what I was doing when debugging
2) if doesnt populate the txt file, then catch it and notify. 
NA
https://usdot-carma.atlassian.net/browse/CDAR-866
VRU use case data analysis
sim pc 1

Potential fix txt file is empty for PET script VRU

---

Contributing.md

This PR is to remove github carma collaborative links in the contribution.md as we are no longer tracking the CARMA collaborative google form.

Update Contributing.md 

---

src/carma-1-tenth/check_distance_to_arrival.py
src/carma-1-tenth/check_port_drayage_ack.py
src/carma-1-tenth/plot_crosstrack_error.py
src/carma-1-tenth/plot_localization.py
src/carma-1-tenth/plot_route_driven.py
src/carma-1-tenth/plot_vehicle_speed.py
src/carma-1-tenth/rosbag_utils.py
src/carma-1-tenth/run_c1t_metric_analysis.py

This PR includes fixes for plots and metrics that will be used for C1T verification testing. Specifically, the fixes include
1. Processing route graphs using the specified nodes/edges instead of fitting a spline through points
2. Adding a buffer to allow the vehicle to accelerate before checking if it is tracking its target speed
3. Adding a check that both incoming MOMs and Rviz goals are reached appropriately
NA
[CF-920](https://usdot-carma.atlassian.net/browse/CF-920)
Adjustments to the data analysis scripts for C1T are needed to account for route graphs that contain branches (i.e. split between standard exit and inspection lane). Additional updates will likely be needed as data analysis with the data collected during integration testing begins.
Tested using data collected during …

Cf 920 finalize scripts

---

src/carma-streets/plot_message_frequencies.py

During the analysis of SDSM message, we found that it generates empty subplots for spat, map etc on the same figure when there is only log data for SDSM. We would like to remove other empty subplots and only generate SDSM subplot on the figure.
This PR is to add a message type argument to indicate only generating subplot for the specified message type.
NA
https://usdot-carma.atlassian.net/browse/FCP-30
CP analysis script
Local testing

CARMA streets plot message frequency script: Add message type argument
